version: '3'

services:
  web:
    image: ghcr.io/argadepp/litehr-web:lts
    ports:
      - "8003:80"
    restart: always  
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./web_data:/var/www/html/hr
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Morya@2143
      MYSQL_DATABASE: hr
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql