version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Morya@2143
      MYSQL_DATABASE: hr
    ports:
      - "3306:3306"
