# Use Ubuntu as the base image
FROM ubuntu:latest

WORKDIR /var/www/html
# Update and upgrade the system
RUN apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata unzip

# Install PHP 8.2 and required extensions
RUN apt-get install -y software-properties-common && \
    add-apt-repository ppa:ondrej/php && \
    apt-get update && \
    apt-get install -y php8.2-mysql php8.2 php8.2-cli php8.2-mbstring php8.2-xml php8.2-zip php8.2-curl php-gd

# Install MySQL Server and Client
RUN apt-get install -y mysql-server mysql-client

# Enable Apache modules
RUN a2enmod rewrite

# Restart Apache
RUN service apache2 restart

# Install Composer
RUN apt-get install -y composer

COPY litehrm.zip .

RUN mkdir hr

COPY litehrm.zip ./hr

RUN cd hr && unzip litehrm.zip

RUN chown -R www-data:www-data *

COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

RUN cd hr && php8.2 artisan key:generate
# RUN php8.2 artisan migrate
# RUN php8.2 artisan storage:link
# Expose port 80 (assuming your web server runs on this port)
EXPOSE 80

# Start Apache in the foreground to keep the container running
CMD ["apache2ctl", "-D", "FOREGROUND"]
